# Image Oficial
# https://quay.io/repository/keycloak/keycloak?tab=tags

FROM quay.io/keycloak/keycloak:12.0.4

ENV KEYCLOAK_USER=admin
ENV KEYCLOAK_PASSWORD=admin

# Não sei o que faz mas no tutorial falava para rodar isso
# RUN /opt/jboss/keycloak/bin/standalone.sh

EXPOSE 8080