# Doc sobre Proxy Reverso
# https://www.hostinger.com.br/tutoriais/proxy-reverso-nginx

FROM nginx

RUN ls /etc/nginx

COPY ./default.conf /etc/nginx/conf.d/default.conf
# RUN service nginx configtest
# RUN service nginx restart


EXPOSE 80 8080